# 데이터/컬럼/학습 설정
data:
  time_col_candidates: ["datetime", "ts", "time", "date"]
  target_col_candidates: ["gen_rate", "y", "y_true", "gen", "target", "power", "pwr"]
  group_col_candidates: ["rto_id", "plant_id", "site_id", "ipp_id"]
  # 로딩 시 CSV 옵션
  parse_dates: true
  tz: "Asia/Seoul"
  # 시간 집계
  resample_rule: "1H"
  duplicate_agg: "mean"

train:
  params:
    n_estimators: 400
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_lambda: 1.0
  scaler: true

eval:
  denom: "p95-p5"
  kpx:
    mode: "rate"          # "rate"(gen_rate 0~1) | "capacity"(kW)
    threshold: 0.001      # 0.1% = 0.001
    pacp_col: "pacp"      # capacity 모드일 때 설비용량 칼럼명

  day_only:
    enabled: true
    start_hour: 6
    end_hour: 18


